version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
  web:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8000:8000