# Generated by Django 4.1.7 on 2023-04-04 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField()),
                ('description_uz', models.TextField(blank=True, max_length=300,
                 null=True, verbose_name='Description in Uzbek')),
                ('description_ru', models.TextField(blank=True, max_length=300,
                 null=True, verbose_name='Description in Russian')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('parent', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('description_uz', models.TextField(blank=True, max_length=300,
                 null=True, verbose_name='Description in Uzbek')),
                ('description_ru', models.TextField(blank=True, max_length=300,
                 null=True, verbose_name='Description in Russian')),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='products', to='product.category')),
            ],
        ),
    ]
