# Generated by Django 4.1.7 on 2023-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_unique_together_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_product_category',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
