# Generated by Django 4.1.7 on 2023-04-04 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(choices=[
                 ('uz', "O'zbek"), ('ru', 'Русский')], default='uz', max_length=2)),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('start', 'Start'), ('select_language', 'Selecting language'), ('ask_phone', 'Waiting for phone number'), ('main_menu', 'Main menu'), ('categories', 'Browsing categories'), ('products', 'Browsing products'), ('amount', 'Choosing amount'), ('basket', 'Basket'), ('order', 'Ordering'), (
                    'settings', 'Settings'), ('confirm_order', 'Confirm order'), ('send_comment', 'Sending comment'), ('select_from_addresses', 'Selecting from addresses'), ('add_address', 'Adding address'), ('address_name', 'Adding address name'), ('address_settings', 'Address settings'), ('choose_payment', 'Choose payment type')], max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('lat', models.DecimalField(decimal_places=17,
                 max_digits=20, null=True, verbose_name='latitude')),
                ('long', models.DecimalField(decimal_places=17,
                 max_digits=20, null=True, verbose_name='longitude')),
                ('comment', models.TextField(null=True)),
                ('payment_method', models.CharField(choices=[('payme', 'Payme'), ('click', 'CLICK'), (
                    'cash', 'Naqd pul'), ('terminal', 'Terminal')], max_length=50, null=True)),
                ('category', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('product', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='session', to='telegram.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='address', max_length=200)),
                ('lat', models.DecimalField(decimal_places=17,
                 max_digits=20, null=True, verbose_name='latitude')),
                ('long', models.DecimalField(decimal_places=17,
                 max_digits=20, null=True, verbose_name='longitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='addresses', to='telegram.user')),
            ],
        ),
    ]
