# Generated by Django 4.1.7 on 2023-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
